### PR TITLE
Making everything use a single structure

### PR DESCRIPTION
**Pull request by swilliamson7**
I think I've addressed all the comments from before, and that this code will run the same as your original code. If you could review the changes again when you have a moment that would be amazing! I've tried to double and triple check that everything will still run, but it's always possible I missed something. I think the other main change was to `output.jl`, I find that the way I've adjusted it still works consistently (knock on wood) but I feel like I remember you finding times it would break?

### CODE REVIEW

**Comment by milankl** [comment]
Also can you delete the `Manifest.toml` ? They are not supposed to be uploaded (it documents which packages with which versions you have installed, and so is the realisation of the compatibility in the `Project.toml`)

**Comment by milankl** [comment]
With https://github.com/milankl/ShallowWaters.jl/commit/cd0cb6a21bd2ef08fa86b1461ca0abcf1e09092f I've just added Checkpointing.jl to extensions, do we need to do the same for Enzyme?

Stupid me did that without a pull request, so I've switched on branch protection for main (requires a pull request and checks to pass)

**Comment by milankl** [comment]
So you can add Checkpointing specific functions that should only load/overload when `using Checkpointing`

**Comment by milankl** [comment]
Did you mean to close this @swilliamson7 ?

**Comment by swilliamson7** [comment]
Yes :)

**Pull request closed without merging**
